# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-29 05:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='visa',
            options={'verbose_name': 'Visa Statu'},
        ),
        migrations.RemoveField(
            model_name='blueprint',
            name='legal_status',
        ),
    ]
