# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-30 22:02
from __future__ import unicode_literals

from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkEnviorment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', django_resized.forms.ResizedImageField(upload_to='img/work-enviorment/temp/')),
                ('session', models.CharField(max_length=511)),
            ],
            options={
                'verbose_name': 'Work Enviorment',
            },
        ),
    ]
