# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-10 07:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queue',
            name='stack',
            field=models.ManyToManyField(blank=True, related_name='queue_stack', to='web.QueueStack'),
        ),
    ]
