# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-11 02:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20170410_0752'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blueprint',
            name='url',
        ),
        migrations.AddField(
            model_name='blueprint',
            name='has_simulator',
            field=models.BooleanField(default=False, verbose_name='Has Simulator'),
        ),
        migrations.AddField(
            model_name='blueprint',
            name='is_closed',
            field=models.BooleanField(default=False, verbose_name='Is Closed'),
        ),
        migrations.AddField(
            model_name='blueprint',
            name='simulator_url',
            field=models.CharField(blank=True, max_length=255, verbose_name='Simulator Url'),
        ),
        migrations.AddField(
            model_name='blueprint',
            name='video_url',
            field=models.CharField(blank=True, max_length=255, verbose_name='Video Url'),
        ),
    ]
