# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-06 09:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_workenviorment'),
    ]

    operations = [
        migrations.CreateModel(
            name='DesiredEmployee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('email', models.CharField(max_length=255, verbose_name='Email Address')),
            ],
            options={
                'verbose_name': 'Desired Employee',
            },
        ),
        migrations.CreateModel(
            name='TestPilots',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=255, verbose_name='Email Address')),
            ],
            options={
                'verbose_name': 'Test Pilot',
            },
        ),
        migrations.RemoveField(
            model_name='blueprinttasks',
            name='expert',
        ),
        migrations.RemoveField(
            model_name='blueprinttasks',
            name='expert_email',
        ),
        migrations.AddField(
            model_name='blueprinttasks',
            name='desired_employee',
            field=models.ManyToManyField(blank=True, related_name='desired_employees', to='web.DesiredEmployee'),
        ),
    ]
