# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-11 22:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_auto_20170411_0231'),
    ]

    operations = [
        migrations.AddField(
            model_name='queuestack',
            name='has_accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='queuestack',
            name='has_applied',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='queuestack',
            name='has_icruited',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='queuestack',
            name='has_interview',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='queuestack',
            name='is_hired',
            field=models.BooleanField(default=False),
        ),
    ]
