# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-12 07:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_auto_20170411_2259'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppliedBlueprints',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('simulator_results', models.CharField(max_length=255, verbose_name='Simulator Results')),
                ('has_completed_simulation', models.BooleanField(default=False)),
                ('blueprint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_blueprint', to='web.Blueprint')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_candidate', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
