# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-12 08:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_appliedblueprints_name_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appliedblueprints',
            name='simulator_results',
            field=models.CharField(blank=True, max_length=255, verbose_name='Simulator Results'),
        ),
    ]
