# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-12 13:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_auto_20170412_0803'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blueprint',
            name='simulator_url',
        ),
        migrations.AddField(
            model_name='appliedblueprints',
            name='has_applied',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='blueprint',
            name='simulator_url_android',
            field=models.CharField(blank=True, max_length=255, verbose_name='Android Job Simulator Url'),
        ),
        migrations.AddField(
            model_name='blueprint',
            name='simulator_url_ios',
            field=models.CharField(blank=True, max_length=255, verbose_name='iOS Job Simulator Url'),
        ),
        migrations.AddField(
            model_name='blueprint',
            name='simulator_url_mac',
            field=models.CharField(blank=True, max_length=255, verbose_name='MacOS Job Simulator Url'),
        ),
        migrations.AddField(
            model_name='blueprint',
            name='simulator_url_win',
            field=models.CharField(blank=True, max_length=255, verbose_name='Windows Job Simulator Url'),
        ),
    ]
