# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-13 01:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_auto_20170412_1304'),
    ]

    operations = [
        migrations.AddField(
            model_name='appliedblueprints',
            name='has_failed',
            field=models.BooleanField(default=False),
        ),
    ]
