# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-15 05:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_prehiredemployee'),
    ]

    operations = [
        migrations.AddField(
            model_name='appliedblueprints',
            name='tasks_completed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='appliedblueprints',
            name='times_failed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='appliedblueprints',
            name='times_tried',
            field=models.IntegerField(default=0),
        ),
    ]
