# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-29 13:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0013_auto_20170419_0614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='preference_filter',
            field=models.TextField(blank=True, null=True, verbose_name='Preference Filter Search'),
        ),
    ]
