# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-01 11:22
from __future__ import unicode_literals

from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0014_auto_20170429_1331'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkEnviorment2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', django_resized.forms.ResizedImageField(upload_to='img/work-enviorment/temp/2/')),
                ('session', models.CharField(max_length=511)),
            ],
            options={
                'verbose_name': 'Work Environment',
            },
        ),
        migrations.AddField(
            model_name='blueprint',
            name='work_enviorment_2',
            field=models.ImageField(blank=True, upload_to='img/work-enviorment/2'),
        ),
        migrations.AlterField(
            model_name='blueprint',
            name='work_enviorment',
            field=models.ImageField(upload_to='img/work-enviorment/1'),
        ),
        migrations.AlterField(
            model_name='workenviorment',
            name='image',
            field=django_resized.forms.ResizedImageField(upload_to='img/work-enviorment/temp/1/'),
        ),
    ]
