# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-12 17:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0015_auto_20170501_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prehiredemployee',
            name='blueprint',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_blueprint_id', to='web.Blueprint'),
        ),
        migrations.AlterField(
            model_name='prehiredemployee',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_user_id', to=settings.AUTH_USER_MODEL),
        ),
    ]
