# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-12 17:19
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0016_auto_20170512_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hiredemployee',
            name='blueprint',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_hired_blueprint', to='web.Blueprint'),
        ),
        migrations.AlterField(
            model_name='hiredemployee',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_hired_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
