# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-18 15:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0018_auto_20170518_1259'),
    ]

    operations = [
        migrations.AddField(
            model_name='blueprint',
            name='video_png',
            field=models.CharField(blank=True, max_length=255, verbose_name='Video Png'),
        ),
    ]
