# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-22 15:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0019_blueprint_video_png'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='preference_filter',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Preference Filter Search'),
        ),
    ]
