# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-23 06:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0023_auto_20170710_0558'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewDateAndTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_and_time', models.CharField(max_length=255, verbose_name='Date & Time')),
                ('for_blueprint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_time_and_date_for_blueprint', to='web.Blueprint')),
            ],
            options={
                'verbose_name': 'Interview Date & Time',
            },
        ),
        migrations.AddField(
            model_name='prehiredemployee',
            name='letter',
            field=models.CharField(blank=True, max_length=511, verbose_name='Interview Letter'),
        ),
        migrations.AddField(
            model_name='prehiredemployee',
            name='location',
            field=models.CharField(blank=True, max_length=255, verbose_name='Interview Location'),
        ),
        migrations.AddField(
            model_name='prehiredemployee',
            name='datetime',
            field=models.ManyToManyField(blank=True, related_name='related_timedate', to='web.InterviewDateAndTime'),
        ),
    ]
