# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-17 03:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0026_help_purpose'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscribed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=256)),
            ],
            options={
                'verbose_name_plural': 'Subscribed',
            },
        ),
    ]
