# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-23 09:22
from __future__ import unicode_literals

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0027_subscribed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workenviorment',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], force_format=None, keep_meta=True, quality=0, size=[800, 600], upload_to='img/work-enviorment/temp/1/'),
        ),
        migrations.AlterField(
            model_name='workenviorment2',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], force_format=None, keep_meta=True, quality=0, size=[800, 600], upload_to='img/work-enviorment/temp/2/'),
        ),
    ]
