# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-21 01:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MetaTags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Page Title')),
                ('page_name', models.CharField(max_length=255, verbose_name='Page Name')),
                ('description', models.CharField(max_length=255, verbose_name='Page Description')),
            ],
            options={
                'verbose_name': 'Meta Tag',
                'verbose_name_plural': 'Meta Tags',
            },
        ),
    ]
